### ISSUE TITLE
Set problem issue

### ISSUE THREAD

**Issue by progfay** [aukkeyikon/Infra_Structure_Strife#1]
1.mouse操作でsetStateを動かしたかったからとりあえずやる
2.ローカルで変化するだけでグローバルじゃないことに気が付く
3.fieldRoadListの中身を書き換えようとしてsetする
4.前後でgetしても中身が変わらない（なんだこれは）

**Comment by progfay** [comment]
どういうことだろうか

**Comment by aukkeyikon** [comment]
void mousePressed 内でmouse下にあるroadに対してsetState()を行う
drawで呼び出しているのはfieldRoadListであるため、変更が反映されない
fieldRoadListにある対象の要素を書き換える必要がある
Arraylistに実装されているset関数を用いて、入れ替えを行おうとした
変更前と変更後をprintln()して確認したところ、入れ替えは発生していなかった
入れ替える対象を間違えているのかとcontains()を行ったところ、fieldRoadListに差し替えるデータは含まれていなかった

**Comment by progfay** [comment]
`fieldRoadList()` method create new ArrayList instance.
So, when you want to save the state of roads, you should make global ArrayList variable.

You should write the code like : 

```java
ArrayList<Road> field;
final float fieldSize=1200;

void setup() {
  field = fieldRoadList(fieldSize/2, fieldSize/2);
}

void draw() {
  for(Road r : field) {
    r.draw();
  }
}

void mousePressed() {
  for(Road r : field) {
    if(r.mousePressed()) {
      r.setState(1);
    }
  }
}
```

does it mean you say?

**Comment by aukkeyikon** [comment]
Thanks, this is exactly what I was looking for.

**Comment by progfay** [comment]
I send PR later.
